# The URL the site will be built for
base_url = "https://nmacun.com"
title = "nurulmac11's blog"
#description = "A zola theme forked from [archie](https://github.com/athul/archie)"

theme = "archie-zola"
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

compile_sass = true

build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "one-dark"
external_links_target_blank = true


[extra]
author = "nurulmac11"
logo_text = "nurulmac11's blog"
favicon = "/favicon.png"
favicon_mimetype = "image/png"

page_titles = "page_only"
external_links_target_blank = true

mode = "toggle"
useCDN = false

# show in the footer
copyright = "keith"

# config your Google Analysis ID
ga = "UA-91588930-1"

# optional: config your i18n entry
[extra.translations]
languages = [{name = "en", url = "/"}]

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "home", url = "/", weight = 2 },
    { name = "about me", url = "/about", weight = 3 },
    { name = "archive", url = "/posts", weight = 2 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "github"
url = "https://github.com/nurulmac11"

[[extra.social]]
icon = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/nrlmcn/"
